/** Каталог предметов. Всё открывается через Вехи Мастерства — органично, через действия игрока. */

import { GroundId, ObjKind } from './types';

export interface CatalogItem {
  id: string;
  name: string;
  hint: string;
  kind: ObjKind;
  /** Размер в тайлах (многоклеточные объекты). */
  w: number;
  h: number;
  /** Шаг сетки при размещении: 1 или 0.25 (четверть-тайлы). */
  step: 1 | 0.5 | 0.25;
  /** Дни реального времени до взрослой формы (0 = сразу готов). */
  growDays: number;
  /** Можно ставить на воду. */
  onWater?: boolean;
  /** Требует воду под собой (мост, лотос). */
  needsWater?: boolean;
  /**
   * Мост должен связывать берега: среди клеток отпечатка обязаны быть
   * и вода, и суша. Иначе дуга ставилась посреди пруда или посреди
   * лужайки и «висела в воздухе».
   */
  spansWater?: boolean;
  /** Можно вращать. */
  rotatable?: boolean;
  tab: string;
}

export interface TerrainBrush {
  id: string;
  name: string;
  hint: string;
  kind: 'ground' | 'water' | 'hill' | 'lower' | 'floor' | 'spring' | 'cascade' | 'steps' | 'terrace';
  ground?: GroundId;
  /** Размер модульного блока. */
  w: number;
  h: number;
  tab: string;
}

export interface CatalogTab {
  id: string;
  name: string;
  icon: string;
  /** Веха, открывающая вкладку. null = открыта с начала. */
  requires: string | null;
}

export const TABS: CatalogTab[] = [
  { id: 'ground', name: 'Земля', icon: 'ground', requires: null },
  { id: 'water', name: 'Вода', icon: 'water', requires: null },
  { id: 'relief', name: 'Рельеф', icon: 'hill', requires: null },
  { id: 'trees', name: 'Деревья', icon: 'tree', requires: null },
  { id: 'stones', name: 'Камни', icon: 'rock', requires: null },
  { id: 'micro', name: 'Мелочи', icon: 'micro', requires: null },
  { id: 'pond', name: 'Пруд', icon: 'lotus', requires: 'first_pond' },
  { id: 'light', name: 'Свет', icon: 'lantern', requires: 'first_evening' },
  { id: 'house', name: 'Усадьба', icon: 'house', requires: 'first_deck' },
  { id: 'shore', name: 'Берег', icon: 'water', requires: 'running_water' },
  { id: 'guests', name: 'Гости', icon: 'bird', requires: null },
];

/**
 * Всё, что зовёт жителей: кормушки, поилки, улей, бельчатник, бревно черепахи.
 * Вольный сад видит их сразу, растущий открывает по одному — как любой предмет.
 */
export const WILD_INVITATION_IDS = ['feeder', 'birdbath', 'beehive', 'squirrel_feeder', 'turtle_log'] as const;

export const TERRAIN_BRUSHES: TerrainBrush[] = [
  {
    id: 'g_moss',
    name: 'Мох',
    hint: 'мягкий ковёр под ногами',
    kind: 'ground',
    ground: 'moss',
    w: 1,
    h: 1,
    tab: 'ground',
  },
  {
    id: 'g_grass',
    name: 'Трава',
    hint: 'светлая полевая трава',
    kind: 'ground',
    ground: 'grass',
    w: 1,
    h: 1,
    tab: 'ground',
  },
  {
    id: 'g_gravel',
    name: 'Гравий',
    hint: 'расчёсанный сад камней',
    kind: 'ground',
    ground: 'gravel',
    w: 1,
    h: 1,
    tab: 'ground',
  },
  {
    id: 'g_sand',
    name: 'Песок',
    hint: 'тёплый светлый песок',
    kind: 'ground',
    ground: 'sand',
    w: 1,
    h: 1,
    tab: 'ground',
  },
  {
    id: 'g_stone',
    name: 'Камень',
    hint: 'плиты и мшистые швы',
    kind: 'ground',
    ground: 'stone',
    w: 1,
    h: 1,
    tab: 'ground',
  },
  {
    id: 'g_soil',
    name: 'Земля',
    hint: 'влажная тёмная почва',
    kind: 'ground',
    ground: 'soil',
    w: 1,
    h: 1,
    tab: 'ground',
  },

  { id: 'w_pond2', name: 'Заводь 2×2', hint: 'маленькое зеркало воды', kind: 'water', w: 2, h: 2, tab: 'water' },
  { id: 'w_pond4', name: 'Пруд 4×4', hint: 'глубокий покой', kind: 'water', w: 4, h: 4, tab: 'water' },
  { id: 'w_stream', name: 'Ручей 1×3', hint: 'вода, что течёт', kind: 'water', w: 1, h: 3, tab: 'water' },
  { id: 'w_fill', name: 'Осушить', hint: 'вернуть землю', kind: 'ground', ground: 'moss', w: 1, h: 1, tab: 'water' },
  {
    id: 'w_spring',
    name: 'Исток 2×2',
    hint: 'вода на высоте — отсюда потечёт',
    kind: 'spring',
    w: 2,
    h: 2,
    tab: 'water',
  },
  { id: 'w_cascade', name: 'Каскад 3×3', hint: 'три ступени вниз с водой', kind: 'cascade', w: 3, h: 3, tab: 'water' },

  { id: 'h_hill3', name: 'Холм 3×3', hint: 'мягкое возвышение', kind: 'hill', w: 3, h: 3, tab: 'relief' },
  { id: 'h_hill2', name: 'Пригорок 2×2', hint: 'едва заметный подъём', kind: 'hill', w: 2, h: 2, tab: 'relief' },
  { id: 'h_low', name: 'Ложбина 3×3', hint: 'опустить землю', kind: 'lower', w: 3, h: 3, tab: 'relief' },
  { id: 'h_steps', name: 'Ступени 1×3', hint: 'подняться по склону', kind: 'steps', w: 1, h: 3, tab: 'relief' },
  {
    id: 'h_terrace',
    name: 'Терраса 4×4',
    hint: 'ровная площадка со стенкой',
    kind: 'terrace',
    w: 4,
    h: 4,
    tab: 'relief',
  },
  {
    id: 'f_deck',
    name: 'Веранда',
    hint: 'тёплые доски энгава',
    kind: 'floor',
    ground: 'deck',
    w: 1,
    h: 1,
    tab: 'relief',
  },
  {
    id: 'f_tatami',
    name: 'Татами',
    hint: 'комната усадьбы',
    kind: 'floor',
    ground: 'tatami',
    w: 1,
    h: 1,
    tab: 'relief',
  },
];

export const ITEMS: CatalogItem[] = [
  // Деревья
  {
    id: 'sakura',
    name: 'Сакура',
    hint: 'неделя до цветения',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 7,
    tab: 'trees',
  },
  {
    id: 'maple',
    name: 'Клён момидзи',
    hint: 'осенью горит багрянцем',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 7,
    tab: 'trees',
  },
  {
    id: 'pine',
    name: 'Сосна',
    hint: 'саженец взрослеет за три дня',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 3,
    tab: 'trees',
  },
  {
    id: 'bamboo',
    name: 'Бамбук',
    hint: 'растёт быстро',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 2,
    tab: 'trees',
  },
  {
    id: 'willow',
    name: 'Ива',
    hint: 'клонится к воде',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 8,
    tab: 'trees',
  },
  {
    id: 'ginkgo',
    name: 'Гинкго',
    hint: 'золотые веера',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 8,
    tab: 'trees',
  },
  {
    id: 'azalea',
    name: 'Азалия',
    hint: 'круглый цветущий куст',
    kind: 'shrub',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 3,
    tab: 'trees',
  },
  {
    id: 'hedge',
    name: 'Стриженый куст',
    hint: 'облако из листвы',
    kind: 'shrub',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 3,
    tab: 'trees',
  },
  {
    id: 'wisteria',
    name: 'Глициния',
    hint: 'весной свисает лиловыми гроздями',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 6,
    tab: 'trees',
  },
  {
    id: 'persimmon',
    name: 'Хурма',
    hint: 'осенью — оранжевые фонарики',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 7,
    tab: 'trees',
  },
  {
    id: 'camellia',
    name: 'Камелия',
    hint: 'цветёт в снегу',
    kind: 'shrub',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 4,
    tab: 'trees',
  },

  // Плодовый сад: взрослые силуэты, собственные сроки цветения и созревания.
  {
    id: 'ume',
    name: 'Умэ',
    hint: 'цветы на изогнутых ветвях, плоды в начале лета',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 7,
    tab: 'trees',
  },
  {
    id: 'nashi',
    name: 'Груша наши',
    hint: 'белое цветение и золотистые круглые груши',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 8,
    tab: 'trees',
  },
  {
    id: 'peach',
    name: 'Персик',
    hint: 'розовые цветы, узкие листья, бархатистые плоды',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 7,
    tab: 'trees',
  },
  {
    id: 'yuzu',
    name: 'Юдзу',
    hint: 'тёмная вечная зелень и жёлтые плоды среди снега',
    kind: 'tree',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 8,
    tab: 'trees',
  },

  // Камни
  {
    id: 'rock_big',
    name: 'Валун 2×2',
    hint: 'грани, прожилки и влажные расщелины',
    kind: 'rock',
    w: 2,
    h: 2,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'stones',
  },
  {
    id: 'rock_mid',
    name: 'Камень',
    hint: 'своя форма, порода и сколы',
    kind: 'rock',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    rotatable: true,
    tab: 'stones',
  },
  {
    id: 'rock_trio',
    name: 'Триада 1×3',
    hint: 'три камня-брата',
    kind: 'rock',
    w: 1,
    h: 3,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'stones',
  },
  {
    id: 'step_stone',
    name: 'Шаговый камень',
    hint: 'шероховатая плита среди мха',
    kind: 'micro',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    tab: 'stones',
  },

  // Мелочи (четверть-тайлы)
  {
    id: 'moss_clump',
    name: 'Подушка мха',
    hint: 'четверть клетки',
    kind: 'micro',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    tab: 'micro',
  },
  {
    id: 'pebbles',
    name: 'Галька',
    hint: 'рассыпать горстью',
    kind: 'micro',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    tab: 'micro',
  },
  {
    id: 'lily',
    name: 'Ландыши',
    hint: 'белые колокольчики',
    kind: 'flower',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 1,
    tab: 'micro',
  },
  {
    id: 'iris',
    name: 'Ирисы',
    hint: 'любят влажный берег',
    kind: 'flower',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 1,
    tab: 'micro',
  },
  {
    id: 'fern',
    name: 'Папоротник',
    hint: 'тень и прохлада',
    kind: 'flower',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 1,
    tab: 'micro',
  },
  {
    id: 'grass_tuft',
    name: 'Пучок травы',
    hint: 'колышется на ветру',
    kind: 'micro',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    tab: 'micro',
  },

  // Пруд (открывается после первой воды)
  {
    id: 'lotus',
    name: 'Лотос',
    hint: 'раскрывается днём',
    kind: 'flower',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 2,
    needsWater: true,
    onWater: true,
    tab: 'pond',
  },
  {
    id: 'lilypad',
    name: 'Кувшинки',
    hint: 'зелёные блюдца',
    kind: 'micro',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 1,
    needsWater: true,
    onWater: true,
    tab: 'pond',
  },
  {
    id: 'bridge',
    name: 'Мостик 1×3',
    hint: 'изогнутая дуга',
    kind: 'bridge',
    w: 1,
    h: 3,
    step: 1,
    growDays: 0,
    rotatable: true,
    onWater: true,
    spansWater: true,
    tab: 'pond',
  },
  {
    id: 'koi',
    name: 'Карпы кои',
    hint: 'ходят кругами',
    kind: 'creature',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    needsWater: true,
    onWater: true,
    tab: 'pond',
  },
  {
    id: 'shishi',
    name: 'Сиси-одоси',
    hint: 'стучит бамбуком',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'pond',
  },

  // Берег (открывается, когда вода пошла)
  {
    id: 'reed',
    name: 'Камыш',
    hint: 'шуршит у самой воды',
    kind: 'flower',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 1,
    tab: 'shore',
  },
  {
    id: 'horsetail',
    name: 'Хвощ',
    hint: 'строгие зелёные стебли',
    kind: 'flower',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 1,
    tab: 'shore',
  },
  {
    id: 'water_stone',
    name: 'Камень в воде',
    hint: 'вода обтекает его',
    kind: 'rock',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    onWater: true,
    needsWater: true,
    tab: 'shore',
  },
  {
    id: 'plank_bridge',
    name: 'Мостки 1×2',
    hint: 'доски над водой',
    kind: 'bridge',
    w: 1,
    h: 2,
    step: 1,
    growDays: 0,
    rotatable: true,
    onWater: true,
    spansWater: true,
    tab: 'shore',
  },

  // Свет
  {
    id: 'lantern_stone',
    name: 'Каменный фонарь',
    hint: 'тёплый огонёк',
    kind: 'lantern',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'light',
  },
  {
    id: 'lantern_paper',
    name: 'Бумажный фонарь',
    hint: 'качается на ветру',
    kind: 'lantern',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'light',
  },
  {
    id: 'lantern_path',
    name: 'Тропный фонарик',
    hint: 'низкий свет у земли',
    kind: 'lantern',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    tab: 'light',
  },
  {
    id: 'brazier',
    name: 'Жаровня',
    hint: 'живой огонь',
    kind: 'lantern',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'light',
  },

  // Усадьба — малые дома (компактные, для мини-садов)
  {
    id: 'tea_house',
    name: 'Чайный домик 2×2',
    hint: 'дом 2×2, бумажные сёдзи, норэн «чай»',
    kind: 'pavilion',
    w: 2,
    h: 2,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'shed',
    name: 'Сарай 1×2',
    hint: 'доски и солома, хранит грабли',
    kind: 'pavilion',
    w: 1,
    h: 2,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'tiny_house',
    name: 'Маленький дом 3×2',
    hint: 'дом 3×2, веранда и тёплый свет',
    kind: 'pavilion',
    w: 3,
    h: 2,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'pavilion',
    name: 'Беседка 2×2',
    hint: 'крыша над головой',
    kind: 'pavilion',
    w: 2,
    h: 2,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'shoji',
    name: 'Сёдзи',
    hint: 'раздвижная стена',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'torii',
    name: 'Тории 1×1',
    hint: 'ворота',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'table',
    name: 'Столик',
    hint: 'чай остывает',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'kotatsu',
    name: 'Котацу',
    hint: 'низкий стол с тёплым стёганым одеялом',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'bookshelf',
    name: 'Книжная полка',
    hint: 'книги, керамика и деревянные полочки',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'engawa_bench',
    name: 'Скамья для веранды',
    hint: 'сиденье с подушкой и чайной чашкой',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'tansu',
    name: 'Низкий шкаф тансу',
    hint: 'деревянные ящики и книги',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'indoor_plant',
    name: 'Растение в керамике',
    hint: 'зелёный уголок комнаты',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'house',
  },
  {
    id: 'tsukubai',
    name: 'Цукубаи',
    hint: 'чаша с водой',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'house',
  },
  {
    id: 'wind_chime',
    name: 'Фурин',
    hint: 'звенит в тишине',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'house',
  },
  {
    id: 'fusuma',
    name: 'Фусума',
    hint: 'перегородка с росписью',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'tokonoma',
    name: 'Токонома',
    hint: 'ниша со свитком',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 1,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'irori',
    name: 'Ирори',
    hint: 'очаг в полу, котелок над огнём',
    kind: 'lantern',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'house',
  },
  {
    id: 'futon',
    name: 'Футон',
    hint: 'постель на татами',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'byobu',
    name: 'Ширма бёбу',
    hint: 'три створки с золотом',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    rotatable: true,
    tab: 'house',
  },
  {
    id: 'bonsai',
    name: 'Бонсай',
    hint: 'сад размером с ладонь',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 5,
    tab: 'house',
  },

  // Гости: сами жители и всё, что их зовёт — подушки, миски, кормушки.
  // Открываются через постройки, а не через задания.
  {
    id: 'cat',
    name: 'Кот',
    hint: 'приходит сам',
    kind: 'creature',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'feeder',
    name: 'Кормушка',
    hint: 'зимний стол для птиц',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'birdbath',
    name: 'Поилка',
    hint: 'пить, купаться, сидеть на краю',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'cushion',
    name: 'Подушка дзабутон',
    hint: 'место для сна',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'bowl',
    name: 'Миска',
    hint: 'на всякий случай',
    kind: 'micro',
    w: 1,
    h: 1,
    step: 0.25,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'beehive',
    name: 'Улей',
    hint: 'гудит в полдень, зовёт пчёл',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'squirrel_feeder',
    name: 'Бельчатник',
    hint: 'домик с орешками для белок',
    kind: 'deco',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'guests',
  },
  {
    id: 'turtle_log',
    name: 'Кормушка для черепахи',
    hint: 'бревно у воды, где греются',
    kind: 'rock',
    w: 1,
    h: 1,
    step: 0.5,
    growDays: 0,
    tab: 'pond',
  },
];

export const ITEM_BY_ID = new Map(ITEMS.map((i) => [i.id, i]));
export const TAB_BY_ID = new Map(TABS.map((t) => [t.id, t]));
export const BRUSH_BY_ID = new Map(TERRAIN_BRUSHES.map((b) => [b.id, b]));

/**
 * Отпечаток предмета с учётом поворота. Якорь предмета привязан
 * к центру его номинального прямоугольника (так он и рисуется),
 * а нарисованный размер при чётном повороте меняет оси местами:
 * мост 1×3 в положении 0 лежит вдоль оси x.
 */
export function footprint(item: CatalogItem, rot: number): { w: number; h: number } {
  return rot % 2 === 0 ? { w: item.h, h: item.w } : { w: item.w, h: item.h };
}

/**
 * Клетки, которые предмет реально занимает: центр как при рисовании,
 * размер — отпечаток с учётом поворота. Граничная клетка, задетая
 * только ребром, не считается.
 */
export function footprintCells(
  item: CatalogItem,
  tx: number,
  ty: number,
  rot: number,
): { x0: number; y0: number; x1: number; y1: number } {
  const cx = tx + item.w / 2;
  const cy = ty + item.h / 2;
  const f = footprint(item, rot);
  return {
    x0: Math.floor(cx - f.w / 2),
    y0: Math.floor(cy - f.h / 2),
    x1: Math.ceil(cx + f.w / 2) - 1,
    y1: Math.ceil(cy + f.h / 2) - 1,
  };
}

/** Вехи мастерства. */
export interface Milestone {
  id: string;
  title: string;
  text: string;
  unlocks: string;
}

export const MILESTONES: Record<string, Milestone> = {
  first_pond: {
    id: 'first_pond',
    title: 'Вода найдена',
    text: 'Вы выкопали первый пруд. Лотосы и мостики теперь ваши.',
    unlocks: 'Пруд',
  },
  first_evening: {
    id: 'first_evening',
    title: 'Сумерки',
    text: 'Сад встретил вечер. Пора зажечь фонари.',
    unlocks: 'Свет',
  },
  first_deck: {
    id: 'first_deck',
    title: 'Порог дома',
    text: 'Доски веранды легли на землю. Усадьба начинается.',
    unlocks: 'Усадьба',
  },
  first_cat: {
    id: 'first_cat',
    title: 'Гость',
    text: 'Кот пришёл сам и остался. Ему нужны подушки и миски.',
    unlocks: 'Подушки и миски',
  },
  running_water: {
    id: 'running_water',
    title: 'Вода пошла',
    text: 'Ручей нашёл дорогу вниз. Теперь в саду слышно течение.',
    unlocks: 'Берег',
  },
  first_steps: {
    id: 'first_steps',
    title: 'Ступени',
    text: 'По склону можно подняться. Сад обрёл высоту.',
    unlocks: 'Рельеф',
  },
  first_terrace: {
    id: 'first_terrace',
    title: 'Терраса',
    text: 'Ровная площадка над садом — есть где поставить беседку.',
    unlocks: 'Рельеф',
  },
  first_path: {
    id: 'first_path',
    title: 'Тропа',
    text: 'Дорожка сама обошла камни и воду. По саду можно гулять.',
    unlocks: 'Мелочи',
  },
  grove: {
    id: 'grove',
    title: 'Роща',
    text: 'Двенадцать деревьев шумят на ветру.',
    unlocks: 'Тишина',
  },
  // --- Вехи, которые замечают, а не требуют ---
  four_seasons: {
    id: 'four_seasons',
    title: 'Круг года',
    text: 'Вы видели этот сад во все четыре времени года.',
    unlocks: 'Круг',
  },
  night_visit: {
    id: 'night_visit',
    title: 'Ночной сад',
    text: 'Вы зашли, когда все спят. Фонари горели для вас одного.',
    unlocks: 'Ночь',
  },
  first_snow: {
    id: 'first_snow',
    title: 'Первый снег',
    text: 'Сад укрыло белым. Камелия цветёт даже сейчас.',
    unlocks: 'Зима',
  },
  in_the_rain: {
    id: 'in_the_rain',
    title: 'Под дождём',
    text: 'Вы остались, когда пошёл дождь. Вода стучит по крыше.',
    unlocks: 'Дождь',
  },
  stone_garden: {
    id: 'stone_garden',
    title: 'Сад камней',
    text: 'Гравий, валуны и ничего лишнего. Здесь думается.',
    unlocks: 'Камни',
  },
  lantern_path: {
    id: 'lantern_path',
    title: 'Дорога огней',
    text: 'Пять фонарей вдоль тропы. Вечером сад светится сам.',
    unlocks: 'Свет',
  },
  full_house: {
    id: 'full_house',
    title: 'Дом обжит',
    text: 'В комнатах есть где спать, где греться и на что смотреть.',
    unlocks: 'Уют',
  },
  koi_pond: {
    id: 'koi_pond',
    title: 'Карпы',
    text: 'Пруд ожил. Кои ходят кругами и никуда не спешат.',
    unlocks: 'Пруд',
  },
  old_tree: {
    id: 'old_tree',
    title: 'Старое дерево',
    text: 'Одно из ваших деревьев выросло полностью. Сосне на это нужно три игровых дня.',
    unlocks: 'Время',
  },
  hundred: {
    id: 'hundred',
    title: 'Сто вещей',
    text: 'В саду сотня предметов, и каждый поставлен вами.',
    unlocks: 'Мастерство',
  },
  // --- Жители: вехи за то, кого заметили, а не за то, что построили ---
  bird_guest: {
    id: 'bird_guest',
    title: 'Пернатые',
    text: 'В саду замечены птицы. Кормушка приглашает их остаться.',
    unlocks: 'Гости',
  },
  first_frog: {
    id: 'first_frog',
    title: 'Голос у воды',
    text: 'У воды поселилась лягушка. В дождь её видно и слышно.',
    unlocks: 'Вода',
  },
  second_cat: {
    id: 'second_cat',
    title: 'Второй кот',
    text: 'Гость обошёл сад и остался: теперь их двое.',
    unlocks: 'Два кота',
  },
  frog_chorus: {
    id: 'frog_chorus',
    title: 'Вечерний хор',
    text: 'Лягушки пели хором, перебивая друг друга. Сад умеет петь и без вас.',
    unlocks: 'Голоса',
  },
  winter_feeder: {
    id: 'winter_feeder',
    title: 'Зимний стол',
    text: 'Зимой у кормушки особенно людно: сад кормит своих.',
    unlocks: 'Забота',
  },
  night_lights: {
    id: 'night_lights',
    title: 'Ночные огни',
    text: 'Над травой зажглись светлячки: тёплой ночью сад светится сам.',
    unlocks: 'Тёплые ночи',
  },
  heron_guest: {
    id: 'heron_guest',
    title: 'Терпеливая гостья',
    text: 'К пруду приходит цапля: большая птица выбирает тихую воду.',
    unlocks: 'Тишина',
  },
  deer_guest: {
    id: 'deer_guest',
    title: 'Олень у рощи',
    text: 'На рассвете к деревьям вышел олень. Сад стал почти лесом.',
    unlocks: 'Лес',
  },
  hedgehog_guest: {
    id: 'hedgehog_guest',
    title: 'Ночной гость',
    text: 'В кустах поселился ёжик. Днём его не видно — только шуршание ночью.',
    unlocks: 'Тихая ночь',
  },
  mouse_guest: {
    id: 'mouse_guest',
    title: 'Кошки и мышки',
    text: 'У кормушки завелись мышки. Коты теперь заняты делом.',
    unlocks: 'Погоня',
  },
  owl_guest: {
    id: 'owl_guest',
    title: 'Ночной дозор',
    text: 'На крыше беседки ухает сова. Мышки теперь прячутся вдвойне.',
    unlocks: 'Уханье',
  },
  squirrel_guest: {
    id: 'squirrel_guest',
    title: 'Прыжок',
    text: 'По соснам пронеслась белка. Где-то в дупле уже спрятаны орешки.',
    unlocks: 'Запасы',
  },
  lizard_guest: {
    id: 'lizard_guest',
    title: 'Солнечный гость',
    text: 'В сухом уголке сада поселилась проворная ящерица.',
    unlocks: 'Жизнь среди камней',
  },
  lizard_bask: {
    id: 'lizard_bask',
    title: 'Впитать солнце',
    text: 'Ящерица отдохнула на прогретом камне. Иногда достаточно просто согреться.',
    unlocks: 'Тепло камня',
  },
  lizard_hunter: {
    id: 'lizard_hunter',
    title: 'Маленький охотник',
    text: 'Ящерица поймала насекомое коротким точным броском.',
    unlocks: 'Жизнь в траве',
  },
  lizard_watch: {
    id: 'lizard_watch',
    title: 'Кошачье любопытство',
    text: 'Кот подкрался к ящерице. В саду встретились два внимательных взгляда.',
    unlocks: 'Тихая встреча',
  },
  lizard_escape: {
    id: 'lizard_escape',
    title: 'Быстрее тени',
    text: 'Почувствовав опасность, ящерица добралась до спасительной щели.',
    unlocks: 'Надёжное укрытие',
  },
  turtle_guest: {
    id: 'turtle_guest',
    title: 'Камень ожил',
    text: 'На камне у пруда греется черепаха. Никуда не спешит.',
    unlocks: 'Тихий час',
  },
  bee_guest: {
    id: 'bee_guest',
    title: 'Гудение',
    text: 'Над цветами загудели пчёлы. Улей зовёт их домой.',
    unlocks: 'Мёд',
  },
};

/** Architecture/furniture must retain scale and orientation, independent of seed. */
export const FURNITURE_IDS = new Set([
  'table',
  'cushion',
  'irori',
  'futon',
  'byobu',
  'fusuma',
  'shoji',
  'tokonoma',
  'bonsai',
  'tansu',
  'indoor_plant',
  'kotatsu',
  'bookshelf',
  'engawa_bench',
]);

export const SMALL_HOUSE_IDS = new Set(['tea_house', 'tiny_house', 'shed', 'pavilion']);
